export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const ADD_SHIPPING_INFO = "ADD_SHIPPING_INFO"
export const ADD_PAYMENT_METHOD_INFO = "ADD_PAYMENT_METHOD_INFO"
export const CART_ITEMS_CLEAR = "CART_ITEMS_CLEAR"

